# Generated by Django 6.1.1 on 2026-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_lanzamiento', models.DateField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('director', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('clasificacion', models.CharField(choices=[('G', 'General'), ('PG', 'Apto para todo público'), ('PG-13', 'Apto para mayores de 13 años'), ('R', 'Restringido'), ('NC-17', 'No apto para menores de 17 años')], max_length=10)),
            ],
        ),
    ]
