# Generated by Django 6.1.1 on 2026-10-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Precio en pesos chilenos', max_digits=6),
            preserve_default=False,
        ),
    ]
