# Generated by Django 6.1.1 on 2026-10-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_pelicula_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='precio',
            field=models.DecimalField(decimal_places=3, help_text='Precio en pesos chilenos', max_digits=10),
        ),
    ]
